apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-gitlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitlab.gitlab.svc.cluster.local/gitlab-instance-128921ea/vfuster-config.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
