Vagrant.configure(2) do |config|
    config.vm.box = "generic/debian12"
    config.vm.synced_folder ".", "/vagrant"
  
    config.vm.define "vfusterS" do |control|
      control.vm.hostname = "vfusterS"
  
      control.vm.network :private_network, ip: "192.168.56.110"
  
      control.vm.provider :virtualbox do |v|
        v.name = "vfusterS"
        v.gui = false
        v.memory = 1024
        v.cpus = 1
      end
  
      control.vm.provision "shell", path: "./install_master.sh"
  
    end
  
    config.vm.define "vfusterSW" do |control|
      control.vm.hostname = "vfusterSW"
  
      control.vm.network :private_network, ip: "192.168.56.111"
  
      control.vm.provider :virtualbox do |v|
        v.name = "vfusterSW"
        v.gui = false
        v.memory = 1024
        v.cpus = 1
      end
  
      control.vm.provision "shell", path: "./install_worker.sh"
    end
  end